name: Fetch Static Secrets example

'on': push

jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Fetch static secrets from Akeyless
      uses: akeyless-community/akeyless-github-action@v1.0.1
      id: fetch-secrets
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        static-secrets: |
          - name: "/S1"
            output-name: "my_first_secret"
  
    - name: Use Akeyless secret (environment variable)
      env:
        SECRET: ${{ env.my_first_secret }}
        HTTP_PROXY: '18.224.107.228:8080'
      run: |
        # Use the secret securely within this step
        echo "Doing something with $SECRET"
        env
     
    - name: Use Akeyless secret (step output)
      run: |
        # Use the secret securely within this step
        
